name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  precommit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Pre-commit checks
        run: npm run precommit:check
